services:
  nop:
    image: nop:1.0
    build: .
    ports:
      - 8080:5000
    networks:
      - nop
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'Developer'
      MSSQL_SA_PASSWORD: 'Pass@123'
    ports:
      - 1433:1433
    volumes:
      - test225:/var/opt/mssql/
    networks:
      - nop

networks:
  nop:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.0.0/24
volumes:
  test225: